### PR TITLE
Allowing converter to run offline

### PR DESCRIPTION
**Pull request by jonathancross**
Taking a snapshot of the bootstrap v3.3.7 dependency so that this tool can run offline.
You can confirm that the snapshot matches original version by checking the hash:

    cat bootstrap_v3.3.7.min.css | openssl dgst -sha384 -binary | openssl base64 -A

Result:

    BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u

(same as listed in the original HTML)

I also added a footer link to github and let people know this runs offline.

TODO: Update README if this is merged.

### CODE REVIEW

**Comment by jonathancross** [comment]
Friendly ping @losh11 @wangxinxi

**Review by losh11 — APPROVED** [review]
tACK. Waiting for at least one more contributor to approve.

**Comment by jonathancross** [comment]
Thank @losh11!
Can you also take a quick look at #9 ?

**Comment by thrasher-** [comment]
Please rebase and then it can be merged.

**Review by thrasher- — APPROVED** [review]
Confirmed integrity of bootstrap file in commit: https://github.com/litecoin-project/p2sh-convert/commit/44a1b27d3d4576b4f4634bbec8deb2cc89c34545

**Pull request merged**
